### ISSUE TITLE
Int from float

### ISSUE THREAD

**Issue by asgraf** [smartemailing/types#126]
I think that float values that can be converted to int without any rounding should not throw exceptions
```php
IntType::from(1.0000000000);//currently throws exception, expected return value of (int) 1
IntType::from('5.00');//currently throws exception, expected return value of (int) 5
```

**Comment by mstrouhal** [comment]
Good idea. Feel free to send PR :)Or, in case it can wait, I will implement this in several days.Odesláno z iPhonu4. 8. 2023 v 14:35, Michał Turek ***@***.***>:﻿
I think that float values that can be converted to int without any rounding should not throw exceptions
IntType::from(1.0000000000);//currently throws exception, expected return value of (int) 1
IntType::from('5.00');//currently throws exception, expected return value of (int) 5

**Comment by mstrouhal** [comment]
https://github.com/smartemailing/types/pull/127
