### ISSUE TITLE
Update consistence/consistence dependency (use 2.0 when possible)

### ISSUE THREAD

**Issue by khorsky** [smartemailing/types#52]
Would it be possible to change consistence dependency to ^1.0 || ^2.0 and tag new version?

I tried to use library within new project and get dependency error...

**Comment by mstrouhal** [comment]
Hello, compatibility with Consistence 2 tested and working. 

Version constraint changed to `^1.0 || ^2.0` in release 1.0.9

https://github.com/smartemailing/types/releases/tag/v1.0.9

Thanks for comment! 👍
